### ISSUE TITLE
sort out chatting bug

### ISSUE THREAD

**Issue by kaiyisg** [ExchangeBuddy/ExchangeBuddy#49]

**Comment by kaiyisg** [comment]
help test the chat socket pls @ZhangHanming

**Comment by WYHNUS** [comment]
Not sure if it's the front-end or back-end issue.
When I post something in the chat, I can see two messages sent by me (which should have been one).
Upon refreshing the page, the number of messages is corrected to one though.

**Comment by kaiyisg** [comment]
@ZhangHanming i tried your method of only emitting 'adduser' the first time i use, and 'switchroom' subsequently whenever i go back to that page.

after 'adduser' (the first time socket is mounted), i am able to send msgs through socket and receive it through the callback

however, after i emit 'switchroom', i am still above to send msgs through socket, but now cannot receive it through the call back. however, it is posted to the server, evident when i make an api call to receive msgs and i see the new msg there

**Comment by WYHNUS** [comment]
I guess this is addressed already? @kaiyisg @ZhangHanming

**Comment by kaiyisg** [comment]
@plsgibchance chatting and events still not working on safari? seems to be ok on mine already! if it is not working pls feedback
